name: pub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

# https://docs.github.com/ja/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pub:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
          swap-storage: false

      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-release@0.24.11

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 10
          submodules: recursive

      - uses: arduino/setup-protoc@v2

      - run: |
          rustup set profile minimal
          rustup update --no-self-update stable
          rustup override set stable

      - run: ./pub.sh
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
